name: Android CI

on:
  push:
    tags:
      - stg.**
      - release.**

env:
  api_url_dev: ${{ secrets.API_URL_DEV }}
  api_url_stg: ${{ secrets.API_URL_STG }}
  api_url_prod: ${{ secrets.API_URL_PROD }}
  sdk_key_dev: ${{ secrets.SDK_KEY_DEV }}
  sdk_key_stg: ${{ secrets.SDK_KEY_STG }}
  sdk_key_prod: ${{ secrets.SDK_KEY_PROD }}

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Apply secrets to properties
        run: |
          echo api_url_dev=\"$api_url_dev\" >> ./secret.properties
          echo api_url_stg=\"$api_url_stg\" >> ./secret.properties
          echo api_url_prod=\"$api_url_prod\" >> ./secret.properties
          echo sdk_key_dev=\"$sdk_key_dev\" >> ./secret.properties
          echo sdk_key_stg=\"$sdk_key_stg\" >> ./secret.properties
          echo sdk_key_prod=\"$sdk_key_prod\" >> ./secret.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --parallel --daemon --continue
